exclude: ".venv|test*|.git"
default_stages: [commit]
fail_fast: false

repos:
  - repo: local
    hooks:
      - id: black-check
        name: black-check
        description: "Black is an automatic Python code formatter. It ensures code readability and PEP8 compliance."
        entry: black src/
        language: system
        pass_filenames: false
        always_run: true
        args:
            - "--line-length=120"

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy-check
        entry: mypy src/
        language: system
        pass_filenames: false
        always_run: true
        args:
            - "--strict"
            - "--ignore-missing-imports"
            - "--allow-untyped-decorators"

  # TODO: Skips with "no files to check"
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: flake8-check
        description: "Flake8 is a command-line utility for enforcing style consistency across Python projects."
        entry: flake8 .
        language: python
        types: [python]
        require_serial: true
        args:
            - "--count"
            - "--max-line-length=130"
            - "--exclude = .venv, build, tests"

  # TODO: Skips with "no files to check"
  - repo: https://github.com/myint/eradicate
    rev: v2.0.0
    hooks:
      - id: eradicate
        name: eradicate-check
        description: "Eradicate removes unused commented code."
        language_version: python3.10
        entry: eradicate
        files: '\.py$'
        args: [ --in-place ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
